// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/service/thesis/interface.go

// Package thesis is a generated GoMock package.
package thesis

import (
	context "context"
	thesis "go-tsukamoto/internal/app/dto/thesis"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockThesisService is a mock of ThesisService interface.
type MockThesisService struct {
	ctrl     *gomock.Controller
	recorder *MockThesisServiceMockRecorder
}

// MockThesisServiceMockRecorder is the mock recorder for MockThesisService.
type MockThesisServiceMockRecorder struct {
	mock *MockThesisService
}

// NewMockThesisService creates a new mock instance.
func NewMockThesisService(ctrl *gomock.Controller) *MockThesisService {
	mock := &MockThesisService{ctrl: ctrl}
	mock.recorder = &MockThesisServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThesisService) EXPECT() *MockThesisServiceMockRecorder {
	return m.recorder
}

// CreateThesis mocks base method.
func (m *MockThesisService) CreateThesis(ctx context.Context, req *thesis.CreateThesisRequest) (*thesis.ThesisResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThesis", ctx, req)
	ret0, _ := ret[0].(*thesis.ThesisResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThesis indicates an expected call of CreateThesis.
func (mr *MockThesisServiceMockRecorder) CreateThesis(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThesis", reflect.TypeOf((*MockThesisService)(nil).CreateThesis), ctx, req)
}

// DeleteThesis mocks base method.
func (m *MockThesisService) DeleteThesis(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteThesis", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteThesis indicates an expected call of DeleteThesis.
func (mr *MockThesisServiceMockRecorder) DeleteThesis(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteThesis", reflect.TypeOf((*MockThesisService)(nil).DeleteThesis), ctx, id)
}

// GetAllTheses mocks base method.
func (m *MockThesisService) GetAllTheses(ctx context.Context) ([]*thesis.ThesisResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTheses", ctx)
	ret0, _ := ret[0].([]*thesis.ThesisResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTheses indicates an expected call of GetAllTheses.
func (mr *MockThesisServiceMockRecorder) GetAllTheses(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTheses", reflect.TypeOf((*MockThesisService)(nil).GetAllTheses), ctx)
}

// GetThesesByUserID mocks base method.
func (m *MockThesisService) GetThesesByUserID(ctx context.Context, userID int) ([]*thesis.ThesisResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThesesByUserID", ctx, userID)
	ret0, _ := ret[0].([]*thesis.ThesisResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThesesByUserID indicates an expected call of GetThesesByUserID.
func (mr *MockThesisServiceMockRecorder) GetThesesByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThesesByUserID", reflect.TypeOf((*MockThesisService)(nil).GetThesesByUserID), ctx, userID)
}

// GetThesisByID mocks base method.
func (m *MockThesisService) GetThesisByID(ctx context.Context, id int) (*thesis.ThesisResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThesisByID", ctx, id)
	ret0, _ := ret[0].(*thesis.ThesisResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThesisByID indicates an expected call of GetThesisByID.
func (mr *MockThesisServiceMockRecorder) GetThesisByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThesisByID", reflect.TypeOf((*MockThesisService)(nil).GetThesisByID), ctx, id)
}

// UpdateThesis mocks base method.
func (m *MockThesisService) UpdateThesis(ctx context.Context, id int, req *thesis.UpdateThesisRequest) (*thesis.ThesisResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThesis", ctx, id, req)
	ret0, _ := ret[0].(*thesis.ThesisResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateThesis indicates an expected call of UpdateThesis.
func (mr *MockThesisServiceMockRecorder) UpdateThesis(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThesis", reflect.TypeOf((*MockThesisService)(nil).UpdateThesis), ctx, id, req)
}
