// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repository/fuzzy/fuzzy.go

// Package fuzzy is a generated GoMock package.
package fuzzy

import (
	context "context"
	models "go-tsukamoto/internal/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFuzzyRepositoryInterface is a mock of FuzzyRepositoryInterface interface.
type MockFuzzyRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFuzzyRepositoryInterfaceMockRecorder
}

// MockFuzzyRepositoryInterfaceMockRecorder is the mock recorder for MockFuzzyRepositoryInterface.
type MockFuzzyRepositoryInterfaceMockRecorder struct {
	mock *MockFuzzyRepositoryInterface
}

// NewMockFuzzyRepositoryInterface creates a new mock instance.
func NewMockFuzzyRepositoryInterface(ctrl *gomock.Controller) *MockFuzzyRepositoryInterface {
	mock := &MockFuzzyRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockFuzzyRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFuzzyRepositoryInterface) EXPECT() *MockFuzzyRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetStudentData mocks base method.
func (m *MockFuzzyRepositoryInterface) GetStudentData(ctx context.Context, studentID int) (*models.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentData", ctx, studentID)
	ret0, _ := ret[0].(*models.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentData indicates an expected call of GetStudentData.
func (mr *MockFuzzyRepositoryInterfaceMockRecorder) GetStudentData(ctx, studentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentData", reflect.TypeOf((*MockFuzzyRepositoryInterface)(nil).GetStudentData), ctx, studentID)
}
